from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
import time

# Start Firefox session and load website
driver = webdriver.Firefox()
driver.get("https://www.selenium.dev/selenium/web/web-form.html")
time.sleep(2)

# Target each field and input text
text_input = driver.find_element(By.XPATH, "//*[@id='my-text-id']")
text_input.send_keys("Text for the text input field.")
time.sleep(.75)
password = driver.find_element(By.XPATH, "/html/body/main/div/form/div/div[1]/label[2]/input")
password.send_keys("ABCD1234")
time.sleep(.75)
text_area = driver.find_element(By.XPATH, "/html/body/main/div/form/div/div[1]/label[3]/textarea")
text_area.send_keys("This is the input for the text area field.")
time.sleep(.75)
drop_select = Select(driver.find_element(By.XPATH, "/html/body/main/div/form/div/div[2]/label[1]/select"))
drop_select.select_by_visible_text("Two")
time.sleep(.75)
drop_list = driver.find_element(By.XPATH, "/html/body/main/div/form/div/div[2]/label[2]/input")
drop_list.send_keys("Los Angeles")
time.sleep(.75)
file_input = driver.find_element(By.XPATH, "/html/body/main/div/form/div/div[2]/label[3]/input")
file_input.send_keys("/Users/ac/Desktop/Screen Shot 2025-06-04 at 3.53.59 PM.png")
time.sleep(.75)
checked_box = driver.find_element(By.XPATH, "//*[@id='my-check-1']")
checked_box.click()
time.sleep(.75)
default_box = driver.find_element(By.XPATH, "//*[@id='my-check-2']")
default_box.click()
time.sleep(.75)
default_radio = driver.find_element(By.XPATH, "//*[@id='my-radio-2']")
default_radio.click()
time.sleep(.75)
color_picker = driver.find_element(By.NAME, "my-colors")
color_picker.send_keys("#00ff00")
time.sleep(.75)
date_picker = driver.find_element(By.XPATH, "/html/body/main/div/form/div/div[3]/label[2]/input")
date_picker.send_keys("06/17/2025")
date_picker.click()
time.sleep(.75)
slider = driver.find_element(By.XPATH, "/html/body/main/div/form/div/div[3]/label[3]/input")
driver.execute_script("arguments[0].value = arguments[1];", slider, "8")
time.sleep(.75)
submit = driver.find_element(By.XPATH, "/html/body/main/div/form/div/div[2]/button")
submit.click()
driver.save_screenshot("Completed Form.png")
